title: Blog Bibliotheks- und Archivinformatik
author: Lea Bächli
email: lea.baechli@stud.fhgr.ch
description: > # this means to ignore newlines until "baseurl:"
  Mein Lerntagebuch im Kurs Bibliotheks- und Archivinformatik FS2020

# social links
github_username:  leabaechli # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: jekyll-theme-minimal
